sudo: required
dist: trusty
language: cpp

install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -y
  - sudo apt-get install -y g++-8
  - g++-8 --version
  - g++ --version
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8
  - g++ --version

script:
  - export PATH=$PATH:$(pwd)/bin
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$(pwd)/lib
  - which u++
  # u++ --version has an exit code of 1 for some reason
  - u++ --version || true
